# .github/workflows/terraform-prod.yml
name: 'Terraform Prod Deployment'

on:
  push:
    branches:
      - main
    paths:
      - 'main.tf'           # Trigger on changes to main.tf
      - 'modules/**'       # Trigger on changes to any module
  workflow_dispatch:       # Allow manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: prod      # GitHub Environment for prod

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}

    # Select prod workspace
    - name: Select Prod Workspace
      run: terraform workspace select prod || terraform workspace new prod

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate
      
    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}

    # Terraform Apply (with manual approval for prod)
    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'  # Only apply on manual trigger
      run: terraform apply -auto-approve tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
