# .github/workflows/terraform-pr.yml
name: 'Terraform PR Check'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'main.tf'
      - 'modules/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - run: terraform init
      - run: terraform workspace select dev || terraform workspace new dev
      - run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}